### ISSUE TITLE
在wsl2中运行出现错误信息

### ISSUE THREAD

**Issue by pluto6496** [sjlleo/nexttrace#106]
在`wsl2`中使用时，达到30跳的最大值后，出现以下错误信息：

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7f0f98]
> 
> goroutine 1 [running]:
> github.com/xgadget-lab/nexttrace/tracemap.GetMapUrl({0xc000696a80, 0x662d})
>         github.com/xgadget-lab/nexttrace/tracemap/tracemap.go:15 +0xb8
> github.com/xgadget-lab/nexttrace/cmd.Excute()
>         github.com/xgadget-lab/nexttrace/cmd/cmd.go:228 +0x168b
> main.main()
>         github.com/xgadget-lab/nexttrace/main.go:8 +0x17

使用了`archlinux`和`ubuntu 22.04` 两个分发，都出现这个错误。

**Comment by tsosunchia** [comment]
详细的命令和输出（包括路由）可以发一下吗？

**Comment by pluto6496** [comment]
```
ntr 13.xxx.xx.97
NextTrace v1.1.3 2023-03-03T07:53:20Z ead7ebb
[NextTrace API] prefered API IP - 104.19.28.108 - 159.39ms
IP Geo Data Provider: LeoMoeAPI
traceroute to 13.xxx.xx.97, 30 hops max, 32 byte packets
1   172.31.240.1    *        [RFC1918]        局域网
                                              0.18 ms / 0.24 ms / 0.27 ms
2   *
3   10.10.1.1       *        [RFC1918]        局域网
                                              33.81 ms / 0.88 ms / 0.79 ms
4   183.xx.xxx.1    AS4134   [APNIC-AP]       中国 广东省 深圳市  chinatelecom.com.cn  电信
                                              2.83 ms / 5.54 ms / 6.29 ms
5   14.xxx.xx.73    AS134774 [CHINANET-GD]    中国 广东省 深圳市  chinatelecom.cn  电信
                                              2.03 ms / 1.93 ms / 1.68 ms
6   183.56.65.69    AS4134   [APNIC-AP]       中国 广东省 深圳市  chinatelecom.com.cn  电信
                                              * ms / * ms / 4.61 ms
7   *
8   202.97.12.1     AS4134   [CHINANET-BB]    中国 广东省   chinatelecom.com.cn  电信
                                              * ms / 108.16 ms / * ms
9   129.250.66.77   AS2914   [NTT-BACKBONE]   美国 佐治亚州 亚特兰大  ntt.net
                                              239.92 ms / 551.03 ms / 651.96 ms
10  129.250.3.23    AS2914   [NTT-BACKBONE]   日本 东京都 东京  ntt.net
                                              196.58 ms / 195.01 ms / 170.62 ms
11  129.250.6.131   AS2914   [NTT-BACKBONE]   日本 东京都 东京  ntt.net
                                              216.04 ms / 316.60 ms / 178.61 ms
12  61.213.161.50   AS2914                    日本 东京都 东京  ntt.net
                                              202.70 ms / 303.15 ms / 308.86 ms
13  *
14  *
15  *
16  52.93.66.143    AS16509                   日本 东京都 东京 AMAZON amazon.com
                                              167.12 ms / 166.70 ms / 167.04 ms
17  *
18  15.230.209.17   *                         新加坡
                                              295.78 ms / 287.95 ms / 290.63 ms
19  52.93.11.61     *                         新加坡
                                              * ms / 231.19 ms / 231.22 ms
20  52.93.11.48     *                         新加坡
                                              139.95 ms / 129.68 ms / 94.41 ms
21  150.xxx.xxx.105 AS16509  [AT-88]          新加坡   AMAZON amazon.com
                                              96.92 ms / 93.11 ms / 92.92 ms
22  150.xxx.xxx.96  *        [AT-88]          新加坡
                                              94.03 ms / 94.50 ms / 93.80 ms
23  *
24  *
25  *
26  *
27  *
28  *
29  *
30  *
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7f0f98]

goroutine 1 [running]:
github.com/xgadget-lab/nexttrace/tracemap.GetMapUrl({0xc000d06a80, 0x66f2})
        github.com/xgadget-lab/nexttrace/tracemap/tracemap.go:15 +0xb8
github.com/xgadget-lab/nexttrace/cmd.Excute()
        github.com/xgadget-lab/nexttrace/cmd/cmd.go:228 +0x168b
main.main()
        github.com/xgadget-lab/nexttrace/main.go:8 +0x17
```

**Comment by pluto6496** [comment]
我这台机器重装过系统，重装前后都有这个问题。
但是在另一台机器的wsl2里面又是正常的

**Comment by tsosunchia** [comment]
trace aws的ip确实经常发生这种事情，你设置一下 max_hop再试试，添加参数 -m 50

**Comment by pluto6496** [comment]
50跳的时候没有报错了

**Comment by tsosunchia** [comment]
> 50跳的时候没有报错了

那大概就是这个问题，大多数网络情况下 hop是小于30的，所以nexttrace默认30，这个问题除了您手动更改max_hop暂时没有更好的办法。

**Comment by pluto6496** [comment]
好的，谢谢
